-- Auth-backed waitlist setup for Syntrae.
-- The landing page sends a Supabase magic link first; this policy only accepts
-- inserts after the visitor has an authenticated session for the same email.

create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null unique,
  full_name text,
  referral_source text,
  status text not null default 'pending',
  consent_to_updates boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint waitlist_email_normalized check (email = lower(trim(email))),
  constraint waitlist_status_check check (status in ('pending', 'invited', 'active', 'unsubscribed'))
);

alter table public.waitlist enable row level security;

revoke insert on table public.waitlist from anon;
revoke all on sequence public.waitlist_id_seq from anon;

grant insert on table public.waitlist to authenticated;
grant usage, select on sequence public.waitlist_id_seq to authenticated;
revoke update on sequence public.waitlist_id_seq from authenticated;

drop policy if exists "Anyone can join waitlist" on public.waitlist;
drop policy if exists "Authenticated verified email can join waitlist" on public.waitlist;

create policy "Authenticated verified email can join waitlist"
on public.waitlist
for insert
to authenticated
with check (
  email = lower(trim(coalesce(auth.jwt() ->> 'email', '')))
  and length(email) between 3 and 320
  and position('@' in email) > 1
  and coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false
  and exists (
    select 1
    from jsonb_array_elements(coalesce(auth.jwt() -> 'amr', '[]'::jsonb)) as auth_method(value)
    where auth_method.value ->> 'method' in ('magiclink', 'otp', 'email/signup')
  )
  and status = 'pending'
  and consent_to_updates = true
);
